### ISSUE TITLE
Can't connect with passwords with a length of more than 62

### ISSUE THREAD

**Issue by lenovouser** [rethinkdb/rethinkdb-ts#17]
In particular with passwords with a length of 64. I tried changing them to 60 and it works.

```
ReqlDriverError: Unable to establish connection, see cause for more info.
{ ReqlDriverError: Unable to establish connection, see cause for more info.
    at RethinkDBConnection.reconnect (<path to project>/node_modules/rethinkdb-ts/lib/connection/connection.js:103:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  msg: 'Unable to establish connection, see cause for more info.',
  _type: 2,
  cause:
   { ReqlAuthError: Wrong password
       at RethinkDBSocket.handleHandshakeData (<path to project>/node_modules/rethinkdb-ts/lib/connection/socket.js:266:27)
       at Socket.socket.on.on.on.on.data (<path to project>/node_modules/rethinkdb-ts/lib/connection/socket.js:80:30)
       at Socket.emit (events.js:182:13)
       at addChunk (_stream_readable.js:283:12)
       at readableAddChunk (_stream_readable.js:264:11)
       at Socket.Readable.push (_stream_readable.js:219:10)
       at TCP.onStreamRead (internal/stream_base_commons.js:94:17)
     msg: 'Wrong password',
     _type: 10,
     cause: undefined,
     name: 'ReqlAuthError',
     term: undefined,
     backtrace: undefined },
  name: 'ReqlDriverError',
  term: undefined,
  backtrace: undefined }
```

**Comment by ronzeidman** [comment]
Interesting, I'm guessing you've tried it with the original driver or the rethinkdbdash one and it works, right?
Maybe I should send the password in chunks? I'll look how the other drivers do it...

**Comment by lenovouser** [comment]
Not too big of an issue, I just 'downgraded' all the passwords to a smaller length.

Yes - I've tried with the original one, and it works.

I am in currently working on switching all of our projects to this driver since it natively supports TypeScript and I've got to say: you did an awesome job here! Thank you so much for creating this!

**Comment by GaikwadPratik** [comment]
Just tested, works upto 62 characters. 63 onwards you get error

**Comment by NetOperatorWibby** [comment]
What a weird, obscure error. 1Password allows for passwords to be 64 characters long so that's the default I generate them at.

This should be in the documentation.

**Comment by maeb** [comment]
The culprit of this bug is the `NULL_BUFFER` being appended to the password buffer:
https://github.com/rethinkdb/rethinkdb-ts/blob/25bb6aa8e2878ce720fde0dafa17294c2e311638/src/connection/connection.ts#L66

This works: ```password = password ? Buffer.from(password) : NULL_BUFFER```
