### ISSUE TITLE
ReqlAuthError on Connection pool

### ISSUE THREAD

**Issue by GaikwadPratik** [rethinkdb/rethinkdb-ts#33]
Here is something weird that I observed:

```
dboptions: {user: 'admin', password: 'incorrectPassword'}
```

if you create a single connection with above option using: 
```
const con = r.connect(dboptions)
```
it throws error: 

```
{ ReqlDriverError: Unable to establish connection, see cause for more info.
    at RethinkDBConnection.reconnect (/opt/hive/services/hive-fabric/node_modules/rethinkdb-ts/lib/connection/connection.js:103:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  msg: 'Unable to establish connection, see cause for more info.',
  _type: 2,
  cause:
   { ReqlAuthError: Wrong password
       at RethinkDBSocket.handleHandshakeData (/opt/hive/services/hive-fabric/node_modules/rethinkdb-ts/lib/connection/socket.js:266:27)
       at Socket.socket.on.on.on.on.data (/opt/hive/services/hive-fabric/node_modules/rethinkdb-ts/lib/connection/socket.js:80:30)
       at Socket.emit (events.js:198:13)
       at Socket.EventEmitter.emit (domain.js:466:23)
       at addChunk (_stream_readable.js:288:12)
       at readableAddChunk (_stream_readable.js:269:11)
       at Socket.Readable.push (_stream_readable.js:224:10)
       at TCP.onStreamRead (internal/stream_base_commons.js:94:17)
     msg: 'Wrong password',
     _type: 10,
     cause: undefined,
     name: 'ReqlAuthError',
     term: undefined,
     backtrace: undefined },
  name: 'ReqlDriverError',
  term: undefined,
  backtrace: undefined }
```
BUT where as if you try to create connectionPool:
```
r.connectPool(dboptions);
```
I get the below error:
```
{ ReqlDriverError: Error initializing pool
    at MasterConnectionPool.once.healthy (/opt/hive/services/hive-fabric/node_modules/rethinkdb-ts/lib/connection/master-pool.js:102:32)
    at Object.onceWrapper (events.js:286:20)
    at MasterConnectionPool.emit (events.js:198:13)
    at MasterConnectionPool.EventEmitter.emit (domain.js:466:23)
    at MasterConnectionPool.setHealthy (/opt/hive/services/hive-fabric/node_modules/rethinkdb-ts/lib/connection/master-pool.js:257:18)
    at ServerConnectionPool.pool.on.on.on.on.healthy (/opt/hive/services/hive-fabric/node_modules/rethinkdb-ts/lib/connection/master-pool.js:248:18)
    at ServerConnectionPool.emit (events.js:203:15)
    at ServerConnectionPool.EventEmitter.emit (domain.js:466:23)
    at ServerConnectionPool.setHealthy (/opt/hive/services/hive-fabric/node_modules/rethinkdb-ts/lib/connection/server-pool.js:129:18)
    at ServerConnectionPool.persistConnection (/opt/hive/services/hive-fabric/node_modules/rethinkdb-ts/lib/connection/server-pool.js:200:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  msg: 'Error initializing pool',
  _type: 3,
  cause: undefined,
  name: 'ReqlDriverError',
  term: undefined,
  backtrace: undefined }
```

This behavior is confusing. Is there anyway that we can get same `ReqlAuthError` if the connection options are incorrect for connection pool as well?

**Comment by GaikwadPratik** [comment]
@ronzeidman ,

Any thoughts?

**Comment by ronzeidman** [comment]
You're right, I'll try to add a cause to the pool initialization error.

**Comment by ronzeidman** [comment]
try the latest version: 2.4.0-rc.16

**Comment by GaikwadPratik** [comment]
Fixed... closing this issue.
Thanks @ronzeidman
