### ISSUE TITLE
Pool status - healthy never get updated?

### ISSUE THREAD

**Issue by kjetilhp** [rethinkdb/rethinkdb-ts#7]
If the server goes down after connected it seems like the connection count and health info isn't updated. see comments inline in the code..

Having the same issue wiht rethinkdbdash
(using latest versions)

example:
```
import { r, MasterPool } from 'rethinkdb-ts'

export class Server {
  pool: MasterPool

  public async connect() {
    let options = {
      host: 'localhost',
      port: 28015,
      db: 'catalog',
      silent: false,
      pingInterval: 1
    }

    // these are never called even though the server are taken down, 
    // or not started at program start but are made available later...

    this.pool = await r.connectPool(options)
    this.pool.on('error', (e) => {
      console.log('error', e)
    })
    this.pool.on('size', (e) => {
      console.log('size', e)
    })
    this.pool.on('available-size', (e) => {
      console.log('available-size', e)
    })
    this.pool.on('healthy', (e) => {
      console.log('healthy', e)
    })
  }

  public check() {
    setInterval(async () => {
      
      // this will continue to print true, 1, 1 even if the server goes down...
      console.log(this.pool.isHealthy)
      console.log(this.pool.getAvailableLength())
      console.log(this.pool.getLength())
      /*
      if (r.getPoolMaster()!.isHealthy) {
        const result = await r
          .table('PhoneCatalog')
          .filter({ callsign: 'xxx' })
          .run()
          .catch(what => {
            console.log('catch', what)
          })       
          console.log(result)
      }
      */
    }, 1000 * 5)
  }
}

let s = new Server()
s.connect()
s.check()
```

rethinkdbdash issue might be related: https://github.com/neumino/rethinkdbdash/issues/366

**Comment by ronzeidman** [comment]
I ran exactly your code but couldn't reproduce this issue:
```
true
1
1
true
0
1
true
1
1
(node:13652) UnhandledPromiseRejectionWarning: ReqlDriverError: The connection was closed before the query could be completed in:
r.error("ping")

    at RethinkDBSocket.close (D:\opensource\rebirthdb-ts\src\connection\socket.ts:238:9)
    at RethinkDBSocket.handleError (D:\opensource\rebirthdb-ts\src\connection\socket.ts:351:10)
    at Socket.socket.on.on.error (D:\opensource\rebirthdb-ts\src\connection\socket.ts:96:34)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:13652) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13652) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
false
0
0
false
0
0
```

**Comment by ronzeidman** [comment]
reconnecting was an issue, I've fixed it. also you cannot start the pool without a valid server, if you want to do that anyway you can now add a config: `waitForHealthy: false` when you `connectPool`.
Please update if the issue is fixed for you in v2.4.0-rc.11
Thanks for reporting!

**Comment by kjetilhp** [comment]
I'm not getting the same output as you when trying,
I cloned your repo, build 
```
rethinkdb-ts@master> npm run build

> rethinkdb-ts@2.4.0-rc.11 build /Users/kjetil/dev/rethinkdb/rethinkdb-ts
> tsc
```
copied the same code as before to the clone folder and I get:
```
true
1
1
// shutting down the container...
true
0
1
true
0
1
//fireing up the container
true
0
1
true
0
1
```
(note: removed most of the debug, I waitet longer before shutting down and restarting)

Only thing that are changed are available length goes to zero, health is still true. Not sure what I'm doing different than you here...

(node v10.13.00, rethinkdb v2.3.6 inside docker)

**Comment by ronzeidman** [comment]
This shouldn't be possible... can you try querying while the container is down? what does it return?

**Comment by ronzeidman** [comment]
The available length doesn't really mean anything since a single connection can run multiple queries simultaneously, it just means that the ping is running.

**Comment by kjetilhp** [comment]
```
Error: connect ECONNREFUSED 127.0.0.1:28015
ReqlDriverError: Unable to establish connection, see cause for more info.
(node:15615) UnhandledPromiseRejectionWarning: ReqlDriverError: Error initializing pool
    at MasterConnectionPool.once.healthy (/Users/kjetil/dev/rethinkdb/rethinkdb-ts/lib/connection/master-pool.js:102:32)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at MasterConnectionPool.emit (events.js:211:7)
    at MasterConnectionPool.setHealthy (/Users/kjetil/dev/rethinkdb/rethinkdb-ts/lib/connection/master-pool.js:260:18)
    at ServerConnectionPool.pool.on.on.on.on.healthy (/Users/kjetil/dev/rethinkdb/rethinkdb-ts/lib/connection/master-pool.js:251:18)
    at emitOne (events.js:121:20)
    at ServerConnectionPool.emit (events.js:211:7)
    at ServerConnectionPool.setHealthy (/Users/kjetil/dev/rethinkdb/rethinkdb-ts/lib/connection/server-pool.js:130:18)
    at ServerConnectionPool.persistConnection (/Users/kjetil/dev/rethinkdb/rethinkdb-ts/lib/connection/server-pool.js:201:26)
(node:15615) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:15615) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error: connect ECONNREFUSED 127.0.0.1:28015
ReqlDriverError: Unable to establish connection, see cause for more info.
Error: connect ECONNREFUSED 127.0.0.1:28015
ReqlDriverError: Unable to establish connection, see cause for more info.
Error: connect ECONNREFUSED 127.0.0.1:28015
ReqlDriverError: Unable to establish connection, see cause for more info.
Error: connect ECONNREFUSED 127.0.0.1:28015
ReqlDriverError: Unable to establish connection, see cause for more info.
(node:15615) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'isHealthy' of undefined
    at Server.<anonymous> (/Users/kjetil/dev/rethinkdb/rethinkdb-ts/my-test.js:80:39)
    at step (/Users/kjetil/dev/rethinkdb/rethinkdb-ts/my-test.js:32:23)
    at Object.next (/Users/kjetil/dev/rethinkdb/rethinkdb-ts/my-test.js:13:53)
    at /Users/kjetil/dev/rethinkdb/rethinkdb-ts/my-test.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/kjetil/dev/rethinkdb/rethinkdb-ts/my-test.js:3:12)
    at Timeout._onTimeout (/Users/kjetil/dev/rethinkdb/rethinkdb-ts/my-test.js:78:42)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:15615) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)
Error: connect ECONNREFUSED 127.0.0.1:28015
ReqlDriverError: Unable to establish connection, see cause for more info.
```
...and so on

**Comment by ronzeidman** [comment]
And that's on the newer version? What OS are you using? Interesting stack
traces. I'll look into it soon.

**Comment by kjetilhp** [comment]
I’m on osx, latest version. Yeah this is rc11.

> 13. nov. 2018 kl. 10:16 skrev Ron Zeidman <notifications@github.com>:
> 
> And that's on the newer version? What OS are you using? Interesting stack
> traces. I'll look into it soon.
>

**Comment by kjetilhp** [comment]
worked better, but still the health state isn't updated when I shut down the server again (see inline comment where that happen..) the events isn't fired anymore 

```
Error: connect ECONNREFUSED 127.0.0.1:28015
ReqlDriverError: Unable to establish connection, see cause for more info.
error event: { ReqlDriverError: Unable to establish connection, see cause for more info.
    at RethinkDBConnection.reconnect (/Users/kjetil/dev/rethinkdb/rethinkdb-ts/lib/connection/connection.js:103:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  msg: 'Unable to establish connection, see cause for more info.',
  _type: 2,
  cause:
   { Error: connect ECONNREFUSED 127.0.0.1:28015
       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
     errno: 'ECONNREFUSED',
     code: 'ECONNREFUSED',
     syscall: 'connect',
     address: '127.0.0.1',
     port: 28015 },
  name: 'ReqlDriverError',
  term: undefined,
  backtrace: undefined }
healthy event: false
size event: 0
Error: connect ECONNREFUSED 127.0.0.1:28015
ReqlDriverError: Unable to establish connection, see cause for more info.
error event: { ReqlDriverError: Unable to establish connection, see cause for more info.
    at RethinkDBConnection.reconnect (/Users/kjetil/dev/rethinkdb/rethinkdb-ts/lib/connection/connection.js:103:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  msg: 'Unable to establish connection, see cause for more info.',
  _type: 2,
  cause:
   { Error: connect ECONNREFUSED 127.0.0.1:28015
       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
     errno: 'ECONNREFUSED',
     code: 'ECONNREFUSED',
     syscall: 'connect',
     address: '127.0.0.1',
     port: 28015 },
  name: 'ReqlDriverError',
  term: undefined,
  backtrace: undefined }
size event: 0
Error: connect ECONNREFUSED 127.0.0.1:28015
ReqlDriverError: Unable to establish connection, see cause for more info.
error event: { ReqlDriverError: Unable to establish connection, see cause for more info.
    at RethinkDBConnection.reconnect (/Users/kjetil/dev/rethinkdb/rethinkdb-ts/lib/connection/connection.js:103:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  msg: 'Unable to establish connection, see cause for more info.',
  _type: 2,
  cause:
   { Error: connect ECONNREFUSED 127.0.0.1:28015
       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
     errno: 'ECONNREFUSED',
     code: 'ECONNREFUSED',
     syscall: 'connect',
     address: '127.0.0.1',
     port: 28015 },
  name: 'ReqlDriverError',
  term: undefined,
  backtrace: undefined }
size event: 0
Error: connect ECONNREFUSED 127.0.0.1:28015
ReqlDriverError: Unable to establish connection, see cause for more info.
error event: { ReqlDriverError: Unable to establish connection, see cause for more info.
    at RethinkDBConnection.reconnect (/Users/kjetil/dev/rethinkdb/rethinkdb-ts/lib/connection/connection.js:103:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  msg: 'Unable to establish connection, see cause for more info.',
  _type: 2,
  cause:
   { Error: connect ECONNREFUSED 127.0.0.1:28015
       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
     errno: 'ECONNREFUSED',
     code: 'ECONNREFUSED',
     syscall: 'connect',
     address: '127.0.0.1',
     port: 28015 },
  name: 'ReqlDriverError',
  term: undefined,
  backtrace: undefined }
size event: 0
false  // starting server around here
0
0
false
0
0
false
0
0
false
0
0
error event: { ReqlDriverError: Failed to connect to localhost:28015 in less than 20s.
    at RethinkDBConnection.reconnect (/Users/kjetil/dev/rethinkdb/rethinkdb-ts/lib/connection/connection.js:122:19)
  msg: 'Failed to connect to localhost:28015 in less than 20s.',
  _type: 5,
  cause: undefined,
  name: 'ReqlDriverError',
  term: undefined,
  backtrace: undefined }
false
0
0
size event: 0
size event: 0
healthy event: true
available-size event: 1
true
1
1
true
0
1
true
0
1
true
1
1
true
0
1
true
1
1
true
1
1
true
1
1
true
0
1
true  // shutdown of server
0
1
true
0
1
true
0
1
true
0
1
true
0
1
true
0
1
true
0
1
true
0
1
true
0
1
```

**Comment by kjetilhp** [comment]
############################
catch { ReqlDriverError: None of the pools have an opened connection and
failed to open a new one.
    at MasterConnectionPool.queue
(/Users/kjetil/dev/rethinkdb/rethinkdb-ts/lib/connection/master-pool.js:134:19)
    at Proxy.<anonymous>
(/Users/kjetil/dev/rethinkdb/rethinkdb-ts/lib/query-builder/term-builder.js:77:67)
    at Server.<anonymous>
(/Users/kjetil/dev/rethinkdb/rethinkdb-ts/my-test.js:92:34)
    at step (/Users/kjetil/dev/rethinkdb/rethinkdb-ts/my-test.js:32:23)
    at Object.next
(/Users/kjetil/dev/rethinkdb/rethinkdb-ts/my-test.js:13:53)
    at /Users/kjetil/dev/rethinkdb/rethinkdb-ts/my-test.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/kjetil/dev/rethinkdb/rethinkdb-ts/my-test.js:3:12)
    at Timeout._onTimeout
(/Users/kjetil/dev/rethinkdb/rethinkdb-ts/my-test.js:79:42)
    at ontimeout (timers.js:436:11)
  msg:
   'None of the pools have an opened connection and failed to open a new
one.',
  _type: 3,
  cause: undefined,
  name: 'ReqlDriverError',
  term: undefined,
  backtrace: undefined }
############################

Den ons. 14. nov. 2018 kl. 20:22 skrev Ron Zeidman <notifications@github.com

**Comment by kjetilhp** [comment]
Just a quick note, tested the exact same setup in a Linux vm on my mac and everything works as expected, only difference is the os and that rethink is running natively instead of in a container, will test some different configurations on osx later..

**Comment by kjetilhp** [comment]
Did some more testing, this time on another mac, same versions - same setup - same code. Results are mainly the same, however, I notice that if I just run the code that checks the health and length without querying, the values never get updated and the events are never fired. If I do have the query in there, the values are updated after a request comes back with an error.

**Comment by ronzeidman** [comment]
try 2.4.0-rc.12, it's after @joakimbeng PR merge

**Comment by kjetilhp** [comment]
seems to work like expected now, great work
